export const FETCH_USERS = 'FETCH_USERS';
export const ACCEPTED_USERS = 'ACCEPTED_USERS';
export const REJECTED_USERS = 'REJECTED_USERS';
export const COUNT_REJECTED = 'COUNT_REJECTED';
export const COUNT_ACCEPTED = 'COUNT_ACCEPTED';
